name: freebsd

on:
  push:
    paths:
      - "**.cpp"
      - "**.h"
      - "**.yml"
      - "**.build"
  pull_request:
    paths:
      - "**.cpp"
      - "**.h"
      - "**.yml"
      - "**.build"

jobs:
  clang:
    runs-on: macos-12 # until https://github.com/actions/runner/issues/385
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD VM
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        prepare: |
          pkg install -y meson pkgconf gtkmm30 nlohmann-json
          pkg install -y gtk-layer-shell
        run: |
          meson setup _build
          meson compile -C _build
